"""Import line"""
# Generated by Django 4.0 on 2022-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    """Class line"""
    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=1,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('login',
                 models.TextField()),
                ('password',
                 models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.FileField(
                upload_to=''),
        ),
    ]
