"""Import line"""
# Generated by Django 4.0 on 2022-02-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Class line"""
    dependencies = [
        ('website', '0002_user_alter_nft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(upload_to='NFT_base_folder/'),
        ),
    ]
