"""Import line"""
# Generated by Django 4.0 on 2022-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    """Class line"""
    dependencies = [
        ('website', '0003_alter_nft_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
