"""Import line"""
# Generated by Django 4.0 on 2022-03-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """Class line"""
    dependencies = [
        ('website', '0004_delete_user_nft_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='owner',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
