# Generated by Django 4.0.3 on 2022-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_nft_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(null=True, upload_to='nft_pack/'),
        ),
    ]
