# Generated by Django 4.0.1 on 2022-05-10 13:29
"""Import line"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Class line"""
    dependencies = [
        ('users', '0003_alter_customuser_profile_pic'),
    ]
    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/users/pictures'),
        ),
    ]
